// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
import type { MapIconGlyph } from './MapIconGlyph';

/** Map symbols from the common pack. Selection is always explicit. */
export const CommonMapIcons = {
  /** Hospital or medical facility. */
  hospital: {
    id: 'hospital',
    pathData: 'M9 3 L15 3 L15 9 L21 9 L21 15 L15 15 L15 21 L9 21 L9 15 L3 15 L3 9 L9 9 Z',
    viewBoxSize: 24,
  },
} as const satisfies Record<string, MapIconGlyph>;
